### ISSUE TITLE
페이지를 크롤링해서 토큰 값 (window.__TOKEN__) 받는 건 twip 측에선 권장하지 않습니다.

### ISSUE THREAD

**Issue by mome0320** [junah201/Twip#1]
![Screenshot_20220126-173800_Chrome.jpg](https://user-images.githubusercontent.com/18746638/151130341-0f99c633-abfe-48c6-b8e6-ceb6d0cfb78c.jpg)

해당 얼럿 박스 소스 일부에 주석을 보면 이 토큰은 만료 시간이 존재하며
서드 파티에서는 권장하지 않고

https://twip.kr/dashboard/security 에서 발급해서 이용하라고 나와 있으므로 그 방침대로 하시는 게 좋아보입니다.

**Comment by junah201** [comment]
@mome0320 
api_token를 사용자가 입력하지 않았을 경우에만 아래와 같은 에러 메시지를 출력하며
```
You don't enter api_token and token_crawl option is False.
Please visit the page below and issue API Token:
https://twip.kr/dashboard/security.

If you want to run with alert_id only, set token_crawl option to True
```
사용자가 token_crawl 옵션을 True로 설정했을 때에만 api_token을 크롤링하고 아래와 같은 경고 메시지를 출력하도록 설정했습니다.
```
You don't enter api_token so you get token from alert box url.
This token has expiration date and is not recommended.
Please visit the page below and issue API Token:
https://twip.kr/dashboard/security.
```

해당 위치에 주석이 있다는 사실은 알았지만, 주의 깊게 보지 않아 해당 문제점이 있는지 모르고 있었습니다. 이슈 감사합니다👍❤️. 다음부터는 주의하도록 하겠습니다.
